fail_fast: true
repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: Ruff check
        entry: ruff check
        args: [--fix]
        language: system
        types: [file, python]
      - id: ruff-format
        name: Ruff format
        entry: ruff format
        language: system
        types: [file, python]